In [3]:
import numpy as np

In [4]:
print("Hello, Jupyter!")


Hello, Jupyter!


In [5]:
lista = [1, 2, 3, 4, 5, 6]
array = np.array(lista)

In [7]:
print(type(lista))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
arr_zeros = np.zeros(10)

print (arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
array[0] = 9
print (array[0]) 
print (array)

9
[9 2 3 4 5 6]


In [14]:
##matrizes
matriz_zeros = np.zeros((5,3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
## notas de alunos
lista_de_notas = [9.8, 5.5, 7.0, 9.1, 3.5, 10.0]

notas = np.array(lista_de_notas)

In [16]:
print('maximo', notas.max())

maximo 10.0


In [17]:
print('minimo',notas.min())

minimo 3.5


In [18]:
print('desvio padrão',notas.std())

desvio padrão 2.392639175099794


In [20]:
print('media',notas.mean())

media 7.483333333333333


In [21]:
print('posição menor', notas.argmin())

posição menor 4
